const fakeData = [
  {
    id: 1,
    companyCode: "facebook",
    companyName: "Facebook",
    jobTitle: "Software Engineering Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [
      {
        author: "Anonymous",
        timestamp: "1h",
        trusted: false,
        text: "Coding challenge out yet?",
        likes: 5,
        liked: false,
        replies: [
          {
            author: "Anonymous",
            timestamp: "56m",
            trusted: true,
            text:
              "Yeah. I've heard they happen on a rolling basis tho so keep that in mind.",
            likes: 5,
            liked: true,
          },
        ],
      },
      {
        author: "Anonymous",
        timestamp: "3h",
        trusted: false,
        text: "Anyone have experience interviewing here?",
        likes: 2,
        liked: false,
        replies: [],
      },
      {
        author: "Anonymous",
        timestamp: "5h",
        trusted: false,
        text: "I've interned here before if anyone has questions",
        likes: 3,
        liked: false,
        replies: [],
      },
    ],
  },
  {
    id: 2,
    companyCode: "google",
    companyName: "Google",
    jobTitle: "Software Engineering Intern",
    status: "Applications available",
    statusStage: 1,
    pay: 7500,
    squares: 840,
    discussion: [],
  },
  {
    id: 3,
    companyCode: "cockroachlabs",
    companyName: "Cockroach Labs",
    jobTitle: "Backend Engineering Intern",
    status: "Applications available",
    statusStage: 1,
    pay: 8000,
    squares: 323,
    discussion: [],
  },
  {
    id: 4,
    companyCode: "linkedin",
    companyName: "LinkedIn",
    jobTitle: "Systems and Infrastructure Engineering Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7800,
    squares: 419,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
  {
    id: 5,
    companyCode: "microsoft",
    companyName: "Microsoft",
    jobTitle: "Software Development Intern",
    status: "Interview selections complete",
    statusStage: 2,
    pay: 7500,
    squares: 675,
    discussion: [],
  },
];

export default fakeData;
