export const job = {
  id: 1,
  shortCode: '8azgnmhT',
  company: {
    shortName: 'mercari',
    name: 'Mercari',
  },
  title: 'Software Engineering Intern',
  status: 'Interview selections complete',
  statusStage: 2,
  pay: 9001,
  squares: 774,
  description: `At Mercari, our mission is to create value in a global marketplace where anyone can buy & sell, and we pride ourselves in taking on a challenge. We are looking for new members to join us in achieving this goal under our values - Go Bold, All for One, and Be Professional.
株式会社メルカリでは「新たな価値を生みだす世界的なマーケットプレイスを創る」というミッションを掲げ、あらゆる挑戦をしています。「Go Bold - 大胆にやろう」「All for One - 全ては成功のために」「Be Professional - プロフェッショナルであれ」という3つのバリューのもと、ミッション達成を共に目指していける仲間を募集しています。`,
  comments: [
    {
      id: 1,
      author: {
        name: 'FuriousRaccoon',
        trusted: false,
      },
      timeString: '1h',
      text: 'Coding challenge out yet?',
      likes: 5,
      liked: false,
      replies: [
        {
          id: 2,
          author: {
            name: 'HissingWalrus',
            trusted: true,
          },
          timeString: '56m',
          text:
            "Yeah. I've heard they happen on a rolling basis tho so keep that in mind.",
          likes: 5,
          liked: true,
          replies: [],
        },
      ],
    },
    {
      id: 3,
      author: {
        name: 'FeignedChameleon',
        trusted: false,
      },
      timeString: '3h',
      text: 'Anyone have experience interviewing here?',
      likes: 2,
      liked: false,
      replies: [],
    },
    {
      id: 4,
      author: {
        name: 'VoraciousMaltese',
        trusted: false,
      },
      timeString: '5h',
      text: "I've interned here before if anyone has questions",
      likes: 3,
      liked: false,
      replies: [],
    },
  ],
};

export const trending = [
  job,
  {
    id: 2,
    shortCode: 'V3XI1QvR',
    company: {
      shortName: 'facebook',
      name: 'Facebook',
    },
    title: 'Software Engineering Intern',
    status: 'Interview selections complete',
    statusStage: 2,
    pay: 7500,
    squares: 675,
    comments: [],
  },
  {
    id: 3,
    shortCode: 'kPYAIoy1',
    company: {
      shortName: 'google',
      name: 'Google',
    },
    title: 'Software Engineering Intern',
    status: 'Coding challenge out',
    statusStage: 2,
    pay: 7500,
    squares: 840,
    comments: [],
  },
  {
    id: 4,
    shortCode: 'g-4HuUAh',
    company: {
      shortName: 'cockroach',
      name: 'Cockroach Labs',
    },
    title: 'Backend Engineering Intern',
    status: 'Applications available',
    statusStage: 1,
    pay: 8000,
    squares: 323,
    comments: [],
  },
  {
    id: 5,
    shortCode: '_NAqzKrA',
    company: {
      shortName: 'linkedin',
      name: 'LinkedIn',
    },
    title: 'Systems and Infrastructure Engineering Intern',
    status: 'Rankings out',
    statusStage: 3,
    pay: 7800,
    squares: 419,
    comments: [],
  },
  {
    id: 6,
    shortCode: 'as7qzKrA',
    company: {
      shortName: 'microsoft',
      name: 'Microsoft',
    },
    title: 'Software Engineering Intern',
    status: 'Applications available',
    statusStage: 1,
    pay: 7200,
    squares: 219,
    comments: [],
  },
  {
    id: 7,
    shortCode: '9HNk_-q2',
    company: {
      shortName: 'pagerduty',
      name: 'PagerDuty',
    },
    title: 'Site Reliability Engineering Intern',
    status: 'Interviews selections complete',
    statusStage: 2,
    pay: 7400,
    squares: 253,
    comments: [],
  },
];
