language: node_js

install:
- nvm install 10.15.3
- yarn install

script:
- grunt symlink
- prettier --check ./web_service/**/**/*.js
- prettier --check ./client/**/**/*.{js,jsx}
- eslint ./web_service/**/**/*.js
- eslint ./client/**/**/*.{js,jsx}
- grunt webpack:once
